# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_collab_pkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='decoded_img',
            field=models.ImageField(upload_to='main_app/static/images'),
        ),
    ]
