# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-09 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='like',
            field=models.ManyToManyField(related_name='likes', to='main_app.User'),
        ),
    ]
